# Generated by Django 4.2.4 on 2023-11-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, null=True)),
                ('videos_qty', models.IntegerField(default=0)),
                ('views_qty', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
